### ISSUE TITLE
Trying to use on 2.8.5

### ISSUE THREAD

**Issue by dschwa** [markn86/moodle-mod_customcert#11]
Client won't let me upgrade them.  grrrrrrrr

I thought I had the mod working. I created 2 templates. Then I tried to add a customcert to a course and it crashed. 
Fatal error: Call to undefined method mod_customcert_mod_form::standard_intro_elements() in /var/www/moodle/mod/customcert/mod_form.php on line 48

Mark, do you have a 2.8 compatible version?

**Comment by markn86** [comment]
Hi, currently I have only been testing on 2.9 and onwards.

That issue arrives due to the replacement of add_intro_editor(). You can fix this by simply changing '$this->standard_intro_elements(get_string('description', 'customcert'));' in mod_form.php to '$this->add_intro_editor(null, get_string('description', 'customcert'));'.

Let me know if you need any more help.

I will think about creating a 2.8 version once I have more time.

**Comment by markn86** [comment]
Also, did you have to change version.php to install this module as I have '$plugin->requires  = 2015051100' set there? Just want to make sure that is working as expected.

**Comment by dschwa** [comment]
I'll try that Mark. Thanks. No need to worry about 2.8 on my part. I've
gotten approval to upgrade in June.

Don

**Comment by dschwa** [comment]
Yes, mark I did need to change all the version.php. Your requires worked

**Comment by markn86** [comment]
Ok, thanks mate. :)
