### ISSUE TITLE
Empty course completion date

### ISSUE THREAD

**Issue by jakubStep** [markn86/moodle-mod_customcert#113]
Dear markn86

Since the course completion is performed via cron, it makes sense that course completion date is also created by cron.

This fact creates an issue - the course completion date is not available instantly after user passed all activities, so date is missing in the certificate if downloaded right after all activities are done.

Many thanks for your help!

**Comment by tluger** [comment]
Hello

I am having a similar issue. There does seem to be a time lag that is related to cron. I do not believe I witnessed this issue all previous times I tested the certificate activity. The scheduled task for completion data is set to run once per minute in Moodle. I wonder if a server setting is interfering with that. Have to check on that.

In the process of testing this, I noticed what appears to be a related issue. If I download a certificate without a date on it, the "bad" certificate is permanently stored on the "My Certificates" page even though I am able to download a correct one later.

I also just noticed that "bad" certificate (the one generated before cron runs, I assume) also does not populate the correct course name. The "bad" one populates the name of our website into that field, which is very odd. Not sure where that is being grabbed from.

I am attaching two certificates for the same course. One is the version stored on the My Certificates page (The_Decoction_Classic_and_Its_Relation_to_the_Shanghan_Lun-8.pdf). This is the same as the one that downloaded right after completing a course. The other is from the same class about 15 minutes afterward (The_Decoction_Classic_and_Its_Relation_to_the_Shanghan_Lun-9.pdf). 

As you can see, the course name is different on each cert. And the date is missing on the bad one.

The way that I know they are from the same class is because there is a hard-coded provider-course number on the lower right of the document that is the same on both files. 

[The_Decoction_Classic_and_Its_Relation_to_the_Shanghan_Lun-8.pdf](https://github.com/markn86/moodle-mod_customcert/files/1033184/The_Decoction_Classic_and_Its_Relation_to_the_Shanghan_Lun-8.pdf)

[The_Decoction_Classic_and_Its_Relation_to_the_Shanghan_Lun-9.pdf](https://github.com/markn86/moodle-mod_customcert/files/1033188/The_Decoction_Classic_and_Its_Relation_to_the_Shanghan_Lun-9.pdf)

**Comment by markn86** [comment]
Hi Tim, your last points will be addressed in #82.

**Comment by markn86** [comment]
Re: the cron - I will need to look into this. Perhaps I can force the recalculation of the date when a certificate is viewed but it has the potential to be a large operation. I need to see if perhaps it can be done on a per-user basis.

**Comment by markn86** [comment]
I looked into this and have to say I am tempted to put this as a "Won't fix". There are places in core where the course is not shown as complete until cron is run.

**Comment by tluger** [comment]
Hi Mark,

I just want to clarify. Are you saying that there are constraints in the core that mean we will just have to live with there being a lag time between the completion of the course and the ability to generate a  certificate with a correct completion date on it?  I completely understand if this is an unfixable issue or if the fix would be so complex that you can't justify the time.  We greatly appreciate all of the work that you've done on creating this excellent plugin. 

The only reason I need clarity is because we may need to update our FAQ to avoid excessive customer service inquiries about this. 

Thanks.

Todd

**Comment by markn86** [comment]
I spoke to other HQ developers and they came to the same conclusion. Sadly the completion API is not great. I can't simply pass a userid to a function to just generate the completion stats for that single user, instead the function does it for all users. The function also contains a huge SQL query, that may change in the future, so I am not really wanting to hardcode something like that into my plugin with changes so it only does it for one user. I would prefer to use the completion API so it is futurepoof. So, at this stage I am going to close this as "Won't fix". Sorry!

**Comment by markn86** [comment]
Also, thanks for the praise. I am glad you are enjoying this plugin! All the best.

**Comment by jakubStep** [comment]
What about some countdown on the cert download page, to make download buton available after some period?? There could be an option cronPeriod in the
custom cert settings, where you can setup minutes for countdown. On the end of the coundown, the download button will be available for download action.

Thank you in advance for your support!

**Comment by tluger** [comment]
The countdown is an interesting idea. We developed kind of a workaround to this issue by setting  course completion to be determined by completing a final quiz. The quiz then unlocked a course survey and completion of the course survey unlocked the certificate. By the time a typical user completed the survey, enough time had elapsed since the completion of the final quiz to trigger the course completion and populate the correct date to the certificate.

**Comment by markn86** [comment]
Sorry for late response.

A setting that waits for the cron to run before the certificate is accessible (with the message explaining the reason it is not accessible to the user) makes sense. So, reopening issue.

I wouldn't want a hard-coded hack in the code that checked if the certificate contained a date element with a completion date and if so checked if the cron had run, so a hook like _can_access_certificate() which elements can define would work.

**Comment by markn86** [comment]
I decided this was going to be an effort and in reality I don't get much time to work on this plugin and there will always be higher priority issues. Considering other parts of Moodle behave the same I am going to just leave it as is.
