### ISSUE TITLE
Date Issued not showing on certificate

### ISSUE THREAD

**Issue by meggatrron** [markn86/moodle-mod_customcert#118]
I'm new to Git so don't blast me if this is the wrong place to post this. I'm working in Moodle 3.3 and have designed a certificate. When logged in as a student (not just the student role) and after completing the requisite lesson, the certificate prinss without showing the date. I've tried the different date modes available with no luck. Any help?

**Comment by markn86** [comment]
What happens when you edit the date element? Does it display when you preview it?

**Comment by meggatrron** [comment]
Hi Mark, 

Yes, when I edit the element and "Save and Preview" I get the current date irrespective of which type of date I set it at. 

Thanks for your help and a great plugin. I plan on contributing to the cause!! 

----- Original Message -----

**Comment by meggatrron** [comment]
Hi Mark, 

Have you made any discovery on this issue? 

Ray 

----- Original Message -----

**Comment by sstoppi** [comment]
Hi Mark,

I have the same problem. I would like to have the Completion Date of the created test in the course), but it doesn't work. ("Topic 3: Test", like shown in the screen Shot). The date only gets displayed when "Save changes and preview".
Any help?

Thanks, Sara
![editingdate](https://user-images.githubusercontent.com/30290487/28365307-4f69da7a-6c88-11e7-850b-d88367eb71cd.PNG)

**Comment by sstoppi** [comment]
Hi Mark, 

do you have updates on this? Thanks,

Sara

**Comment by markn86** [comment]
Hi Sara,

Have you had a look at https://github.com/markn86/moodle-mod_customcert/issues/113?

**Comment by markn86** [comment]
Hi Ray,

I will be working on issues next week for this plugin, so expect an update then. Cheers for your patience.

(Note - I have been overseas for a few weeks and majority of the time I did not have access to the internet, sorry for the late reply).

**Comment by meggatrron** [comment]
No worries Mark. Your Custom Certificate Plugin is absolutely awesome! I have been working with it as is using the "Date Printed" until you figure out what it needs. 

Thank you. 

----- Original Message -----

**Comment by markn86** [comment]
Hi Ray,

I did the following -

1. Enabled completion on the site.
2. Created a new course with a start and end date.
3. Enrolled a student into the course.
4. Added an assignment to the course and set it so it was marked as complete when a student made a submission.
5. Set the course completion to be dependent on this activity being set.
6. Created a custom certificate with 5 date elements (every option available).
7. Logged in as the student and downloaded the certificate.
    - The only dates being shown were the course start date, course end date and the issue date.
8. Submitted the assignment.
9. Ran the site cron.
10. As the student I downloaded the certificate again.
    - The only dates being shown were the course start date, course end date, completion date and the issue date.

I then wondered why the date of the assignment was not displaying and had a look at the code. It is supposed to display the date that it was graded but this isn't possible because the function it is calling only returns the grade. So there is indeed a bug!

Working on fix now.

**Comment by markn86** [comment]
This has been fixed now. I will update the plugin in the Moodle plugins DB at the end of the week. Thanks for your patience and the report.

**Comment by meggatrron** [comment]
Thank you for the update Mark!! 

----- Original Message -----

**Comment by piteko** [comment]
Hi,
I saw that you fixed and published two different commits respectively for the 3.2 and 3.3 moodle version. Is there a commit for the moodle 3.1 plugin (which is the only long-term release)?
Thanks!
Marcello

**Comment by markn86** [comment]
Hi Marcello,

Since I develop this in my own time I only support versions that align with the Moodle release - having an additional version to test on is time consuming. Also, this is not a security issue which is why I never backported it. Feel free to cherry-pick the commit for you to use.

Sorry. :)
