### ISSUE TITLE
Allow users to verify certificates via a Moodle webservice

### ISSUE THREAD

**Issue by gcavalcante8808** [markn86/moodle-mod_customcert#138]
Hello Friends,

Is there anyway to verify a certificate using just a GET request?

Something like: http://lms.local/mod/customcert/verify_certificate.php?contextid=158&code=UIENRI

This question is fuelled by the necessity of a simple element to render QRCodes inside the certificate to verify a issued cert. For now, I Just created a simple project which is working form me (though It need more work on UI options, and a more elegant logic for the form skip:

https://github.com/gcavalcante8808/moodle-mod_customcert_qrcode

Thanks in advance.

**Comment by markn86** [comment]
Hi Gabriel,

Sorry for the delayed response. I was over in Sydney for the Australian Moodlemoot.

This is a good idea. However, I think the proper approach would be to create a Moodle webservice rather than passing an optional param to the URL.

If I was to create a webservice would you simply want the webservice to return true/false. Would that suffice?

**Comment by gcavalcante8808** [comment]
Hi,

A webservice would be great indeed, but if it returns some basic data (Course, Moodle Site Name, Student Name) the possibilities would be amazing.

**Comment by markn86** [comment]
Closing as I will create a solution in #208 (when I get time to work on it). Thanks for your help!
