### ISSUE TITLE
Profile change that doesnt change custom certificate

### ISSUE THREAD

**Issue by mgaiotti** [markn86/moodle-mod_customcert#141]
I am not a developer so I'm not sure if I can explain this.  Is there a way to make the custom certificate not change if someone changes their profile name.  We want to set it to if a person gets a certificate that certificate is good for just them.  (i'm also not sure this is the right place for this question so I apologize if it isn't.)

**Comment by markn86** [comment]
Hi, thanks for the report.

Currently this is not possible as the certificate is dynamically generated each time the user clicks to download it. However, it would be possible if #38 was implemented as we could serve the PDF that was saved at the time it was created, rather than generating it each time.

I am going to close this issue as it will be resolved by #38 .. now I just need to find the time to implement it. :)
