### ISSUE TITLE
Certificate Preview pulls today's date instead of course start date

### ISSUE THREAD

**Issue by emmarichardson** [markn86/moodle-mod_customcert#144]
1.  Add a date field set to course start date.
2.  Click on Save and Preview.
3.  Downloaded Certificate shows current date, not course start date.
4.  Certificate generated by Download Certificate button DOES show the correct date.

While I understand that this is just a preview, it is confusing for the date to be incorrect.  I actually originally thought that the field was not pulling correctly.  For my course creators, I always have them preview to make sure it looks correct.  They are going to call me every time to tell me the date is wrong!!

**Comment by markn86** [comment]
Hey Emma,

You make a good point.

The reason for this approach is because the user editing the certificate may not have any information for particular elements. For example, adding a grade element would render no grade for the teacher, but would for students, so during the preview mode it uses a dummy value.

I think the best approach here would be to go through the elements and see if we should use dummy data, or real data.

**Comment by emmarichardson** [comment]
Ah that makes sense - not sure how hard it would be but perhaps if you could add an indicator when using dummy data - or even "Actual Grade will go here" text or something similar.  That would clear up confusion across all fields.  But, yes, going through and checking to see if you could use the actual data or not would definitely help.  Thanks.

**Comment by markn86** [comment]
List of fields I think warrant changing in this issue -

1. Grade
2. Date

**Comment by markn86** [comment]
What I did with this fix was mention on the Reposition page that it's just example data and when rendering the PDF for a preview it will say for the grade and the date that it's just an example.
