### ISSUE TITLE
Add QR code element

### ISSUE THREAD

**Issue by markn86** [markn86/moodle-mod_customcert#146]
This has been requested a few times.

**Comment by michael-milette** [comment]
I really like the idea of having a URL link encoded as a QR code which points back to the originating Moodle site where it will the person an image of the same certificate. Through comparison, if it doesn't match exactly, you'll know it is a fake.

**Comment by gcavalcante8808** [comment]
For now, I'm using the following implementation:

https://github.com/gcavalcante8808/moodle-mod_customcert/tree/MOODLE_32_STABLE/element/qrcode

@michael-milette can you provide more details about the statement "Through comparison, if it doesn't match exactly, you'll know it is a fake." ?

**Comment by michael-milette** [comment]
1. You give a hiring manager a copy of the certificate.
2. He/she scans the QR code.
3. This takes them to the moodle site which displays the certificate on their screen. They do not need to be logged-in or even have an account.

If the name/course/date, etc. don't match up exacly when compared visually, that means the certificate they were given was faked.

Someone may have copied someone elses certificate, for example, and replaced the name.

For extra assurance, include a photo of the student on the certificate.

Let me know if you have any other questions. 

Best regards,

Michael

**Comment by gcavalcante8808** [comment]
@michael-milette Yeah, thats it, I'm using in the way that you described. With this, we achieved a no paper solution on our environment.

**Comment by michael-milette** [comment]
@gcavalcante8808, some people might express privacy concerns.

My suggestion would be to add an option in the settings that would additionally require the verifiyer to enter an authentication code in order to view the certificate. For example, if enabled, the QR code would automatically have a caption which says something like "Authentication code: FFF" where the FFF would be the hex representation of the last 3 digits of their user id.

That way nobody could simply randomly access certificates by sequentially entering urls.

**Comment by michael-milette** [comment]
Even better - make it the last 4 characters of an md5 hash of the user id.

**Comment by gcavalcante8808** [comment]
@michael-milette The verify_certificate page actually is a form where you insert the code and the data is returned; the qrcode, is the same thing, without the need to insert the code because it its already coded in the URL. The only protection that we now is the verifyany field (which make possible or not to verify a certificate as an guest user).

**Comment by michael-milette** [comment]
Sounds good to me. :-)

**Comment by markn86** [comment]
Looks like we should probably be using https://github.com/endroid/qr-code as https://github.com/aferrandini/phpqrcode seems abandoned - I am going to see how difficult this will be to change.

**Comment by brendanheywood** [comment]
@markn86 are you simply after a qr code encoder? If so I think there is one hidden deep inside core already:

```
require_once($CFG->libdir.'/tcpdf/tcpdf_barcodes_2d.php');
$barcode = new TCPDF2DBarcode($qrcodeurl, 'QRCODE');
$image = $barcode->getBarcodePngData(15, 15);
echo html_writer::img('data:image/png;base64,' . base64_encode($image),''));
```

https://github.com/catalyst/moodle-local_qrlinks/issues/14

**Comment by markn86** [comment]
Ah, great! Thanks Brendan.

**Comment by markn86** [comment]
I added one, but needs a bit more testing before I am happy to release it as stable.

**Comment by markn86** [comment]
Closing, please create separate issues if you find anything.

**Comment by JorgeDHernandez** [comment]
Hi Mark!

Many thanks for add code QR for Moodle 3.5. It´s works perfect whit out authentication!

**Comment by mdjnelson** [comment]
You're welcome! Glad it is useful. :)
