### ISSUE TITLE
Error 500 Internal Server Error

### ISSUE THREAD

**Issue by lixusrarnavo** [markn86/moodle-mod_customcert#156]
I recently just installed customcert in my moodle server. I extracted the files in the mod folder, the site sent me the notifications of new plugin installation and proceeded to install it. Everything went right, I got no error during the installation whatsoever. But right after I add a certificate to a course and try to access it I get internal server error 500, all I could search was because of permission issue, but still configuring the view.php file to have more permissions still would get me error, and after checking error_log file from my server I get this:

PHP Warning:  PHP Startup: SourceGuardian: Unable to initialize module
Module compiled with module API=20160303
PHP    compiled with module API=20131226
These options need to match
 in Unknown on line 0

My guess is because I'm using moodle 3.4 and php 7? Or is it something else?
Thanks in advance for your answers.

**Comment by markn86** [comment]
Hi,

Thanks for the report.

Moodle 3.4 requires PHP 7 to install, so this is not the problem.

This issue seems to be a mismatch between the PHP module 'SourceGuardian' and your PHP version as they were compiled against different versions.

You could try to upgrade the modules and see if that helps, otherwise Google to find a solution.
