### ISSUE TITLE
Make it clear what 'Completion date' refers to

### ISSUE THREAD

**Issue by thepurpleblob** [markn86/moodle-mod_customcert#160]
One of the options for a date element is 'Completion date'. What is that? Completion date of what?

My course doesn't have completion enabled and - possibly not surprisingly - no date is generated on the certificate.

**Comment by markn86** [comment]
This should really be asked in the Moodle forums as it is not an area for support but to keep track of bugs/improvements. :)

The completion date is when the user was recognised as completing the course. This happens when the cron runs and figures out who has completed a course and inserts that data in the course_completions table.

**Comment by thepurpleblob** [comment]
Sorry - I should have been clearer. This confused more than one user - and me. That's what I assumed it meant but I think it could be a bit clearer. A warning about Completion not being enabled and/or grey out this option would be an improvement.

**Comment by markn86** [comment]
Ok, reopened. I'll add more information to the help tip so it is more clear. Thanks.

**Comment by markn86** [comment]
I added some logic to only show that option if completion is enabled.

**Comment by thepurpleblob** [comment]
Thanks!
