### ISSUE TITLE
Feature Request: please allow to print "Date of Birth" from user profile

### ISSUE THREAD

**Issue by rochelmeyer** [markn86/moodle-mod_customcert#163]
Hi, 
our certificates are required to carry First Name, Last Name and DOB to clearly identify the person that has completed an activity. 
I did not find an option to print the Date of Birth from the user Profile. 
As a workaround i currently use a different - otherwise unused - field within the user profile, which might lead to problems if users or colleagues accidentally change that field. 
Thanks!

**Comment by michael-milette** [comment]
Hi @rochelmeyer 

Where would you find the DOB in Moodle? It is not one of the default fields. Are you using a custom user profile field? If so, there are settings for custom profile fields, one of which is to lock the field so that user cannot change it. There is also a setting to completely hide it so that users can't even see it.

Naturally, users with administrative type roles would still have access to that information but, if you can't trust them to not mess with that kind of information, you probably shouldn't be giving them that kind of access to your website.

Best regards,

Michael Milette

**Comment by markn86** [comment]
Closing, thanks Michael.

There is already an option to add custom profile fields to the certificate and that is where a DOB field belongs.
