### ISSUE TITLE
Months names are not displayed in russian in PDF file

### ISSUE THREAD

**Issue by Jarvil** [markn86/moodle-mod_customcert#177]
Hello,

If you force course language to Russia the months names on the certificate are displayed as question 
marks 

**10 ???? 2018**

when it should read

**10.04.2018**

Is this a bug?

**Comment by tbahula** [comment]
I just checked our Russian certificates. The date appears as expected both with "force language" and with user selected language.
![image](https://user-images.githubusercontent.com/14959510/38563045-f420ad4a-3ca9-11e8-8d29-6461b58614af.png)

Plugin version: 2016052320
Moodle version: 3.1.9 (Build: 20171113)
--

**Comment by Jarvil** [comment]
Hello,

Yes but is it in the PDF-file also? @tbahula 

I forced the course language to russia and it's also users preferred language it still shows ????. When Im editing the certificate and go to page where you can drag elements it shows month name in russia but when you download the certificate PDF it is ????

mod_customcert 3.3 release (Build: 2017050508) and Moodle 3.3.5 (Build: 20180319)

![cert0](https://user-images.githubusercontent.com/15193418/38597383-01cfdfae-3d60-11e8-9fb0-6ab422745048.PNG)

![cert1](https://user-images.githubusercontent.com/15193418/38597376-fa73e386-3d5f-11e8-842f-01043a41527d.PNG)

![cert2](https://user-images.githubusercontent.com/15193418/38597379-fdd3ae26-3d5f-11e8-9e1f-30facb4cfdd6.PNG)

![certpdf](https://user-images.githubusercontent.com/15193418/38597388-064ced74-3d60-11e8-9988-e888d9833e0e.PNG)

**Comment by tbahula** [comment]
@Jarvil , sorry that I wasn't clearer in my description. Yes, the month names appear in Russian as expected both in the certificate definition and in the resulting PDF.
![image](https://user-images.githubusercontent.com/14959510/38630381-c410e1fc-3d84-11e8-9fa3-4be10c664bef.png)

**Comment by michael-milette** [comment]
@tbahula 

In Moodle, calendars and dates often get their text from the operating system. In order to have the date appear in Russian, you may need to install the Russian language pack to your operating system. For example, in Ubuntu, you would use the following commands at a shell terminal prompt:

sudo apt-get install language-pack-ru
sudo service apache2 reload

You can test to see if the language pack was properly installed by using the following command:

sudo locale -a

If this command shows that the language pack is installed but it is still not working for you, you may need to restart the operating system for the changes to take effect.

If you are using a different operating system than Ubuntu, please check your operating system's documentation on how to complete a similar procedure.

Hope this helps.

Best regards,

Michael

**Comment by Jarvil** [comment]
Hello,

We have russian locale on our server:

`sudo locale -a
C
C.UTF-8
en_US.utf8
fi_FI.utf8
POSIX
ru_RU.utf8
sv_SE.utf8`

still the custom certificate PDF shows ???? and not the month name in russia. 
Course forced language is russia and also the users language is russia and when you add the date-element to the certificate you can see the month name in russia but in PDF-file it's ????

How is the PDF-file generated? Does it bypass locale-settings? Where does it pick the month name from? @markn86 @bobopinna 

![rus1](https://user-images.githubusercontent.com/15193418/40960979-f6bfe738-68a9-11e8-86bb-2cf7a7ca96b4.png)
![rus2](https://user-images.githubusercontent.com/15193418/40960986-f96d0e84-68a9-11e8-9716-b13d56af8e07.png)
![rus3](https://user-images.githubusercontent.com/15193418/40960991-fbdea0d8-68a9-11e8-97ee-4ad67d9effa6.png)
![rus4](https://user-images.githubusercontent.com/15193418/40960993-fd7f8060-68a9-11e8-8409-0b7d856dc08e.PNG)

**Comment by Jarvil** [comment]
Hello,

We figured out what the problem was Font that I choose when I created the Date-field in the certificate. Time Roman didn't work but Freezer works.

**Comment by markn86** [comment]
Thanks for the update on this issue. Sorry for the late response from myself.
