### ISSUE TITLE
Plugin Architecture Question

### ISSUE THREAD

**Issue by joshwillcock** [markn86/moodle-mod_customcert#193]
Hello Mark,

Thankyou for working on the great old certificate plugin and now on this awesome replacement.
With regards to migrating to this plugin, is the architecture similar enough that we could use a script to migrate the old certificate modules to the new format.

From my understanding we'd need to migrate each certificate setting and then create the new instance. If this isn't possible I'd be interested to know why this replacement module was created and not just improved on the prior. I've inherited a rather large system with literally thousands of courses which would need updating so I would struggle to manually migrate everything?

Thanks in advance,

Josh

**Comment by markn86** [comment]
Hi Josh,

Unfortunately it was not possible because the old certificate module (mod_certificate) allowed the user to create a .php file that decided how the certificate would look. It was not possible for me to parse this and somehow transfer the logic (which could be anything) into the new plugin.

Please see https://moodle.org/mod/forum/discuss.php?d=229683 for more information.
