### ISSUE TITLE
Create page to display the list of custom certificates belonging to a user

### ISSUE THREAD

**Issue by markn86** [markn86/moodle-mod_customcert#44]
This would be a useful feature.

**Comment by robsoncardosoti** [comment]
Hello. 
Congratulations for the plugin.
I need to digitally sign certicates. 
You think you can use this code [](https://tcpdf.org/examples/example_052) in a new element?
I'm trying but i could not.
Thank you.

**Comment by markn86** [comment]
Done.

**Comment by whipper81** [comment]
Hi,
It looks like the certificates only appear on the "My Certificates" page after they've been viewed once on the individual courses (After the "Get your certificate" button is clicked).  Is it possible to allow the certificates to be viewed on this page if the student has not clicked that button the course page? 

Students are expecting to see certificates on this page since they successfully passed the course, but only the ones that were already viewed show here. That's a bit confusing. Is there a way around that?

**Comment by markn86** [comment]
Hmm, the page simply looks at the customcert_issues table for any certificates the user has obtained. I suppose the logic could be changed but it would be a lot harder to implement as we would have to look for every certificate in the system and check if the user has access to it. Can you create another issue for this request as it is a new functionality request and not a bug with the current issue.

**Comment by whipper81** [comment]
Sure, doing that now.

**Comment by tluger** [comment]
Hi

This was my request last Fall, and I am happy to see that it has been implemented. Where does the student find the My Certificates page?

Thanks.

Todd

**Comment by markn86** [comment]
There will be a 'My certificates' link in their profile.

**Comment by tluger** [comment]
Thanks for building this!

**Comment by markn86** [comment]
You're welcome! :)
