### ISSUE TITLE
Add ability to verify certificates

### ISSUE THREAD

**Issue by markn86** [markn86/moodle-mod_customcert#51]
Again, another useful feature.

**Comment by Gotrekk** [comment]
it would be nice to add QR code for the verification :)

**Comment by goryntsev** [comment]
Hi, Mark,
I am a heavy user of your old certificate plugin along with the [verify certificate block](https://moodle.org/plugins/block_verify_certificate). This verifying function is very important as my students often provide their unique certificate code in their CVs an as a teacher I promise them lifetime verification on the web site. I would be glad to move to your new certificate plugin but that means that I should also keep both the old plugin and its related verification block so that my students, who used it before, could verify their "old" certificates. It might be quite confusing.
Is it possible to add to the new plugin verification function an ability to verify certificates issued under the old one? If this function were available I would remove the old verification block from my site but keep the old plugin itself with its issued certificates table in the database available for the queries from the new plugin. I think it would be appreciated by thousands of other users of your software.

**Comment by markn86** [comment]
Hi Alexander,

I honestly don't like the idea of tying the two plugins together like that. The codebases should remain separate and they should act independently. I can understand your situation and how having two places to verify a code is confusing but hacking some code so that it checks a table from another plugin doesn't sit well with me.

I will need to think about it.

**Comment by goryntsev** [comment]
Hi Mark,

Apparently you had your reasons why you started the custom certificate as a project separated from the old plugin. But if they were just two generations of the same software piece then it would use the same database table and this issue with verification would not appear at all. Maybe one day you decide to merge them :)
Thanks for what you do.

**Comment by markn86** [comment]
Hi Alexander,

The mod_certificate activity certificate types are highly customisable as users can write any code they wish in their certificate type located in mod/certificate/type/<typetheyareusing>/certificate.php. However, the mod_customcert activity stores the details of the certificate's appearance in the database. To convert the existing mod_certificate types I would have to interpret the code in each type a user has created and copy this into the database - which is not possible.

**Comment by markn86** [comment]
Closing this.

You can now do basic verification via the menu option 'Verify certificate' in the activity settings menu. The QR code is a good idea but requires a lot of work, so can be addressed in another issue.

**Comment by Zell1000** [comment]
Ciao Mark,
Prima di tutto grazie per questo splendido plug-in.
Vorrei chiederti se è possibile numerare i certificati rilasciati.

Quindi come elemento "certificato numero "xx".

Naturalmente il numero deve essere incrementale relativamente ad ogni corso...
spero tu possa aiutarmi.

Grazie

------------------------


Hi Mark,
First of all thank you for this beautiful plug-in.
I would like to ask you if you can number issued certificates.

So as an element certificate"number xx".

Of course, the number must be incremental relative to each course ...
I hope you can help me.

Thank you
