### ISSUE TITLE
Fix repositioning elements with images 404

### ISSUE THREAD

**Issue by jeffvee** [markn86/moodle-mod_customcert#55]
Running 3.1.1+ with latest customcert plugin. No debug errors except console saying the image is 404. 

Whenever I upload a image, select it with the element (bgimage), and head to the reposition section the image 404's.

**Comment by Tw0bit** [comment]
Any update to this at all? Its a bit hard to design the certificates without the background image.. great module - this is the only issue we have.

**Comment by markn86** [comment]
Sorry guys, all my development time at the moment is being spent on the 3.2 release. I am really under the gun to fix all the issues with the new messaging UI. Once the release is out of the way I will dedicate a week to this as there are a lot of things on the backlog to look at!

**Comment by zapperpro** [comment]
The problem is connected to old function names in some files.

For example in file lib.php in line 237:
`// We are positioning the elements.
    if ($filearea === 'image') {
        if ($context->contextlevel == CONTEXT_MODULE) {
            require_login($course, false, $cm);
        } else if ($context->contextlevel == CONTEXT_SYSTEM && !has_capability('mod/certificate:manage', $context)) {
            return false;
        }`

U need to rename the 
`has_capability('mod/certificate:manage', $context)`

to
`has_capability('mod/customcert:manage', $context)`

This is only an example. There are still some other files uses the 'certificate' naming. By renaming them in code, it was possible to make the backend image work again. I didnt test all possible outputs, but for my needs it worked. I didnt found the solution on my own. So I dont deserve credit ;) ... But I hope it will help you.

**Comment by markn86** [comment]
Great find Stefan! Updating now ..
