### ISSUE TITLE
Table "customcert_templates" does not exist

### ISSUE THREAD

**Issue by pavelsokolov** [markn86/moodle-mod_customcert#75]
I am using this module for quite some time, but this commit (ee3bdf7c1828e930a88286ced51df8ed6efad012) brings in the error. We've never had such a table 'customcert_templates' in neither of our moodle instances...

**Comment by pavelsokolov** [comment]
Found it: 43d20c0d1b7a3f93eb292f15b282d2909f349073 adds a new table in favour of old ones, but there is no appropriate function in update.php.

**Comment by markn86** [comment]
Hey Pavel,

Sorry for that.

The reason for this is because the module was still in beta (see https://github.com/markn86/moodle-mod_customcert/commit/43d20c0d1b7a3f93eb292f15b282d2909f349073#diff-5bbd3ccd25214f9956eea7e9f714bc08) so I did not write an upgrade script.

However, the module has been in stable condition for some time now so I am including upgrade paths when necessary.

Sorry for the inconvenience.

**Comment by pavelsokolov** [comment]
I see, no problem. I will probably just create that table manually.
