### ISSUE TITLE
Date format

### ISSUE THREAD

**Issue by aortizl** [markn86/moodle-mod_customcert#97]
Hi, thank you for reading this.
I'm using your custom certificate plugin and think is great, unfortunately I've experienced one recurrent issue: my Moodle site runs in spanish and once I've configured the certificate to use the user date (which is set to spanish format) it works fine
![errorcert1](https://cloud.githubusercontent.com/assets/27018718/24809149/3f4edf14-1b84-11e7-97c4-fb5935faf630.png)

But randomly after some time the date starts appearing with only the MONTH in english and I need to reconfigure 60+ certificates by hand AGAIN. 
![errorcert2](https://cloud.githubusercontent.com/assets/27018718/24809219/75c34670-1b84-11e7-9c2c-a331c8e1caf6.jpg)

Am I doing something wrong? Is there anything that I'm not configuring correctly, either on the Moodle admin or the plugin?

Thanks in advance.
AOL

**Comment by markn86** [comment]
Thanks for the report. Seems like a bug to me. Strange that it happens after a certain amount of time though. Is the date changing?

**Comment by aortizl** [comment]
Hi, 
when I setup the certificate and test it, it works fine and prints correctly. The courses are open so each user can get through anytime. When a user finishes, answers the quiz and aproves, can view and get the certificate. Every user has date in latinamerican format. Some users get their certificate correctly and some others get the date with the error. I don't know what to seek in order to fix this.

**Comment by markn86** [comment]
I am not able to replicate this.

I am almost sure it must be a Moodle issue since the date element is simply calling userdate() which then lets Moodle handle all the logic.

I suggest perhaps checking https://docs.moodle.org/32/en/Language_FAQ#I.27ve_set_a_default_site_language.2C_but_the_Moodle_calendar_is_in_English._Why.3F.

If you are able to provide step-by-step productions so that I can produce this on my machine that would be great!
